version: "3"

services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            - MONGO_DATA_DIR=./data/db
            - MONGO_LOG_DIR=./dev/null
        networks:
            - app-network
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 5s
            timeout: 15s
            retries: 4

    rabbitmq:
        image: rabbitmq:latest
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - app-network
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 15s
            retries: 4

    user-service:
        build: ./user-service/.
        ports:
            - 3000:3000
        depends_on:
            mongo:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network

    notification-service:
        build: ./notification-service/.
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
